services:
  - type: web
    name: flickhive-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: SECRET_ACCESS_TOKEN
        sync: false
      - key: SECRET_REFRESH_TOKEN
        sync: false
      - key: CORS_ORIGIN
        sync: false
